volumes:
  postgres-fin-new-app-volume:
    driver: local
  frontend-node-modules:
    driver: local
  nginx-certs:
    driver: local

services:
  postgres-fin-new-app:
    image: ${POSTGRES_IMAGE}
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_APP_USER: ${POSTGRES_APP_USER}
      POSTGRES_APP_PASSWORD: ${POSTGRES_APP_PASSWORD}
    ports:
      - "${POSTGRES_HOST_BIND}:${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
    volumes:
      - postgres-fin-new-app-volume:/var/lib/postgresql/data
      - ./docker/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - fin-new-app
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9500:80"
    volumes:
      - ./Backend:/var/www
    env_file:
      - ./Backend/.env
    environment:
      APP_ENV: ${BACKEND_APP_ENV}
      APP_DEBUG: ${BACKEND_APP_DEBUG}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_CONTAINER_PORT}
      DB_NAME: ${POSTGRES_DB}
      DATABASE_URL: "postgresql://${POSTGRES_APP_USER}:${POSTGRES_APP_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_CONTAINER_PORT}/${POSTGRES_DB}?serverVersion=${POSTGRES_SERVER_VERSION}&charset=${POSTGRES_CHARSET}"
      XDEBUG_MODE: ${XDEBUG_MODE}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
    depends_on:
      - postgres-fin-new-app
    networks:
      - fin-new-app
  frontend:
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
      target: development-env
    container_name: frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5173:5173"
    volumes:
      - ./frontEnd:/app
      - frontend-node-modules:/app/node_modules
    env_file:
      - ./frontEnd/.env
    environment:
      FRONTEND_RUNTIME_MODE: ${FRONTEND_RUNTIME_MODE:-development}
    depends_on:
      - backend
    networks:
      - fin-new-app
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx-fin-new-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-certs:/etc/nginx/certs
    environment:
      - NGINX_SELF_SIGNED_CERT_SUBJECT=${NGINX_SELF_SIGNED_CERT_SUBJECT:-/CN=localhost}
    depends_on:
      - backend
      - frontend
    networks:
      - fin-new-app

networks:
  fin-new-app:
    driver: bridge
