<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260428210008 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entry_type_id INT NOT NULL, transaction_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2B219D70E9AA2304 ON entry (entry_type_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2B219D702FC0CB0F ON entry (transaction_id)');
        $this->addSql('CREATE TABLE entry_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE expense (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, installments INT NOT NULL, expense_transaction_id INT NOT NULL, expense_type_id INT NOT NULL, expense_payment_method_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D3A8DA6983042F1 ON expense (expense_transaction_id)');
        $this->addSql('CREATE INDEX IDX_2D3A8DA6A857C7A9 ON expense (expense_type_id)');
        $this->addSql('CREATE INDEX IDX_2D3A8DA6B207993C ON expense (expense_payment_method_id)');
        $this->addSql('CREATE TABLE expense_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE payment_method (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(5, 2) NOT NULL, location VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, month INT NOT NULL, year INT NOT NULL, transaction_wallet_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_723705D13202BBB0 ON transaction (transaction_wallet_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, status BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, role INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE wallet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(50) NOT NULL, description VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status BOOLEAN NOT NULL, wallet_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7C68921FD66FF683 ON wallet (wallet_user_id)');
        $this->addSql('ALTER TABLE entry ADD CONSTRAINT FK_2B219D70E9AA2304 FOREIGN KEY (entry_type_id) REFERENCES entry_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE entry ADD CONSTRAINT FK_2B219D702FC0CB0F FOREIGN KEY (transaction_id) REFERENCES transaction (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA6983042F1 FOREIGN KEY (expense_transaction_id) REFERENCES transaction (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA6A857C7A9 FOREIGN KEY (expense_type_id) REFERENCES expense_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA6B207993C FOREIGN KEY (expense_payment_method_id) REFERENCES payment_method (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D13202BBB0 FOREIGN KEY (transaction_wallet_id) REFERENCES wallet (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wallet ADD CONSTRAINT FK_7C68921FD66FF683 FOREIGN KEY (wallet_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE entry DROP CONSTRAINT FK_2B219D70E9AA2304');
        $this->addSql('ALTER TABLE entry DROP CONSTRAINT FK_2B219D702FC0CB0F');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA6983042F1');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA6A857C7A9');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA6B207993C');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D13202BBB0');
        $this->addSql('ALTER TABLE wallet DROP CONSTRAINT FK_7C68921FD66FF683');
        $this->addSql('DROP TABLE entry');
        $this->addSql('DROP TABLE entry_type');
        $this->addSql('DROP TABLE expense');
        $this->addSql('DROP TABLE expense_type');
        $this->addSql('DROP TABLE payment_method');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE wallet');
    }
}
